---
title: "Keyword_emotion_detection"
author: "Hongfeng Ai"
date: "13 March 2019"
output: html_document
---

```{r, include=FALSE}
options(warn=-1)
library(ROAuth)
library(rtweet)
library(dplyr) 
library(forcats)
library(twitteR)
library(tm)
library(plyr)
library(stringr)
library(scales)
library(RColorBrewer)
library(igraph)
library(syuzhet)
library(plotly)
library(fmsb)
```

### Emotion radar chart
I use the NRC emotion lexicon to detect emotions in a text. the negative and positive (sentiment polarity) detection are removed in here and only show eight emotions (trust, anticipation, sadness, joy, anger, fear, surprise and disgust). We calculate the percentage of each emotions per candidate on the tweets with mentioning them.
```{r}
# import csv data
# isretweet: 0-import all, 1-only retweet, 2-exclude retweet
import_data <- function(csv_file, isretweet){
     file <- read.csv(csv_file)
     if (isretweet == 0){
          keyword <- filter(file, lang == "en")
     }else if (isretweet == 1){
          keyword <- filter(file, lang == "en" & is_retweet != "FALSE")
     }else if (isretweet == 2){
          keyword <- filter(file, lang == "en" & is_retweet == "FALSE")
     }
     
     return(keyword)
}

Trump_keyword <- import_data("Trump_keyword.csv", 2)
Julian_keyword <- import_data("Castro_keyword.csv", 2)
Kamala_keyword <- import_data("Harris_keyword.csv", 2)
AOC_keyword <- import_data("Ocasio_Cortez_keyword.csv", 2)
Bernie_keyword <- import_data("Sanders_keyword.csv", 2)
eWarren_keyword <- import_data("Warren_keyword.csv", 2)

# clean the text
clean_tweets_func <- function(DATASET){
     clean_tweets = DATASET$text
     # remove retweet entities
     clean_tweets = gsub('(RT|via)((?:\\b\\W*@\\w+)+)', '', clean_tweets)
     # remove at people
     clean_tweets = gsub('@\\w+', '', clean_tweets)
     # remove punctuation
     clean_tweets = gsub('[[:punct:]]', '', clean_tweets)
     # remove numbers
     clean_tweets = gsub('[[:digit:]]', '', clean_tweets)
     # remove html links
     clean_tweets = gsub('http\\w+', '', clean_tweets)
     # remove unnecessary spaces
     clean_tweets = gsub('[ \t]{2,}', '', clean_tweets)
     clean_tweets = gsub('^\\s+|\\s+$', '', clean_tweets)
     # remove emojis or special characters
     clean_tweets = gsub('<.*>', '', enc2native(clean_tweets))
     # lowercase
     clean_tweets = tolower(clean_tweets)
     return(clean_tweets)
}


# Count emtion
emotion_pert_func <- function(keyword_data, NAME){
     clean_tweets = clean_tweets_func(keyword_data)
     emotions<- get_nrc_sentiment(clean_tweets)
     emo_bar = colSums(emotions)
     emo_sum = data.frame(count=emo_bar, emotion=names(emo_bar))
     emo_sum$emotion = factor(emo_sum$emotion, levels=emo_sum$emotion[order(emo_sum$count, decreasing = TRUE)])
     emo_sum <- emo_sum[1:8,]
     emo_sum$percent<-(emo_sum$count/sum(emo_sum$count))*100
     
     emo_pert = t(emo_sum$percent)
     row.names(emo_pert) <- NAME
     colnames(emo_pert) <-emo_sum$emotion
     return (emo_pert)
}

Trump_emo_pert = emotion_pert_func(Trump_keyword, "Donald Trump")
Bernie_emo_pert = emotion_pert_func(Bernie_keyword, "Bernie Sanders")
Julian_emo_pert = emotion_pert_func(Julian_keyword, "Julian Castro")
Kamala_emo_pert = emotion_pert_func(Kamala_keyword, "Kamala Harris")
Elizabeth_emo_pert = emotion_pert_func(eWarren_keyword, "Elizabeth Warren")
AOC_emo_pert = emotion_pert_func(AOC_keyword, "Alexandria Ocasio-Cortez")

# if we plot all six candidates togethere, then the graph will looks messy, so we separe them into two graph and each graph only compares with 3 candidates in here 
comp_emo_df1 <- rbind(Trump_emo_pert, Kamala_emo_pert, AOC_emo_pert)
comp_emo_df2 <- rbind(Bernie_emo_pert, Julian_emo_pert, Elizabeth_emo_pert)

# convert to data.frame type
comp_emo_df1 <- as.data.frame(comp_emo_df1)
comp_emo_df2 <- as.data.frame(comp_emo_df2)

# To use the fmsb package, I have to add 2 lines to the dataframe: the max and min of each topic to show on the plot!
comp_emo_df1 = rbind(rep(30,5) , rep(0,5) , comp_emo_df1)
comp_emo_df2 = rbind(rep(30,5) , rep(0,5) , comp_emo_df2)

# radarchart with custom features
colors_border=c( rgb(0.2,0.5,0.5,0.9), rgb(0.8,0.2,0.5,0.9) , rgb(0.2,0.2,0.5,0.9) )
colors_in=c( rgb(0.2,0.5,0.5,0.4), rgb(0.8,0.2,0.5,0.4) , rgb(0.2,0.2,0.5,0.4) )
radarchart( comp_emo_df1  , axistype=1 , 
            #custom polygon
            pcol=colors_border , pfcol=colors_in , plwd=1 , plty=1,
            #custom the grid
            cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.8,
            #custom labels
            vlcex=0.8 
)
legend(x=0.7, y=1, legend = rownames(comp_emo_df1[-c(1,2),]), bty = "n", pch=20 , col=colors_in , text.col = "grey", cex=1.2, pt.cex=3)

radarchart( comp_emo_df2  , axistype=1 , 
            #custom polygon
            pcol=colors_border , pfcol=colors_in , plwd=1 , plty=1,
            #custom the grid
            cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.8,
            #custom labels
            vlcex=0.8 
)

legend(x=0.7, y=1, legend = rownames(comp_emo_df2[-c(1,2),]), bty = "n", pch=20 , col=colors_in , text.col = "grey", cex=1.2, pt.cex=3)

```